govendor fetch github.com/Kitt-AI/snowboy/swig/Go
govendor fetch gobot.io/x/gobot/...
govendor fetch google.golang.org/api/speech/v1
govendor fetch google.golang.org/api/language/v1
govendor fetch google.golang.org/api/googleapi/transport
govendor fetch github.com/satori/go.uuid
govendor fetch github.com/Kitt-AI/snowboy/swig/Go
govendor fetch github.com/googollee/go-socket.io
govendor fetch github.com/gin-gonic/gin@v1.2