# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/Kitt-AI/snowboy"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/currantlabs/ble"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/sse"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/googollee/go-engine.io"

[[constraint]]
  branch = "master"
  name = "github.com/googollee/go-socket.io"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/errwrap"

[[constraint]]
  branch = "master"
  name = "github.com/jasonlvhit/gocron"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.0.9"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/mgutz/logxi"
  version = "1.0.0"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/raff/goble"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/sigurn/utils"

[[constraint]]
  name = "github.com/tucnak/telebot"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[constraint]]
  name = "gobot.io/x/gobot"
  version = "1.11.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v8"
  version = "8.18.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
